### ISSUE TITLE
Cambios solicitados

### ISSUE THREAD

**Issue by CarlosRubioTNM** [amyazc/pr-ctica#1]
Buen trabajo, jóvenes.

Ahora requiero que hagan los siguientes cambios en su sitio:

1. Corregir las faltas de ortografía en la página (por ejemplo: "Mèxico", "a- tención", "integra", entre otras). Revisen toda la página para encontrar los demás errores.
2. Añadir la Misión y Visión (inventadas) de la empresa.
3. Cambien las tarjetas de los integrantes del equipo para que las 3 tengan el mismo ancho.

Cuando terminen los cambios, me avisan por medio de este hilo y lo reviso. Saludos.

**Comment by amyazc** [comment]
Cambios realizados:)

**Comment by CarlosRubioTNM** [comment]
Excelente, jóvenes. Cierro el issue. 👍
